import React from "react";

export const levels = [
    {title:'Sweet Will',text:" #|1|# is a document #|2|#"},
    {title:'iCitizen',text:' #|2|# an individual of the #|0|#'},
    {title:'Economy',text:' #|0|# or #|1|#'},
    // {title:'Sweet Economy',text:" #|3|# testing 44444 #|0|#"},
    // {title:'iCitizen',text:' #|2|# an individual of the Sweet Economy'},
    // {title:'Economy',text:' #|0|# or sweet economy'},
    // {title:'Sweet Will',text:" #|1|# is a document #|2|#"},
    // {title:'iCitizen',text:' #|2|# an individual of the Sweet Economy'},
    // {title:'Economy',text:' #|0|# or sweet economy'},
    // {title:'Sweet Will',text:" #|1|# is a document #|2|#"},
    // {title:'iCitizen',text:' #|2|# an individual of the Sweet Economy'},
    // {title:'Economy',text:' #|0|# or sweet economy'},
    // {title:'Sweet Will',text:" #|1|# is a document #|2|#"},
    // {title:'iCitizen',text:' #|2|# an individual of the Sweet Economy'},
    // {title:'Economy',text:' #|0|# or sweet economy'},
    // {title:'Sweet Will',text:" #|1|# is a document #|2|#"},
    // {title:'iCitizen',text:' #|2|# an individual of the Sweet Economy'},
    // {title:'Economy',text:' #|0|# or sweet economy'},
    // {title:'Sweet Will',text:" #|1|# is a document #|2|#"},
    // {title:'iCitizen',text:' #|2|# an individual of the Sweet Economy'},
    // {title:'Economy',text:' #|0|# or sweet economy'},
    // {title:'Sweet Will',text:" #|1|# is a document #|2|#"},
    // {title:'iCitizen',text:' #|2|# an individual of the Sweet Economy'},
    // {title:'Economy',text:' #|0|# or sweet economy'},
    // {title:'Sweet Will',text:" #|1|# is a document #|2|#"},
    // {title:'iCitizen',text:' #|2|# an individual of the Sweet Economy'},
    // {title:'Economy',text:' #|0|# or sweet economy'},
    // {title:'Sweet Will',text:" #|1|# is a document #|2|#"},
    // {title:'iCitizen',text:' #|2|# an individual of the Sweet Economy'},
    // {title:'Economy',text:' #|0|# or sweet economy'},
    // {title:'Sweet Will',text:" #|1|# is a document #|2|#"},
    // {title:'iCitizen',text:' #|2|# an individual of the Sweet Economy'},
    // {title:'Economy',text:' #|0|# or sweet economy'},
    // {title:'Sweet Will',text:" #|1|# is a document #|2|#"},
    // {title:'iCitizen',text:' #|2|# an individual of the Sweet Economy'},
    // {title:'Economy',text:' #|0|# or sweet economy'},
    // {title:'Sweet Will',text:" #|1|# is a document #|2|#"},
    // {title:'iCitizen',text:' #|2|# an individual of the Sweet Economy'},
    // {title:'Economy',text:' #|0|# or sweet economy'},
    // {title:'Sweet Will',text:" #|1|# is a document #|2|#"},
    // {title:'iCitizen',text:' #|2|# an individual of the Sweet Economy'},
    // {title:'Economy',text:' #|0|# or sweet economy'},
    // {title:'Sweet Will',text:" #|1|# is a document #|2|#"},
    // {title:'iCitizen',text:' #|2|# an individual of the Sweet Economy'},
    // {title:'Economy',text:' #|0|# or sweet economy'},
    // {title:'Sweet Will',text:" #|1|# is a document #|2|#"},
    // {title:'iCitizen',text:' #|2|# an individual of the Sweet Economy'},
    // {title:'Economy',text:' #|0|# or sweet economy'},
    // {title:'Sweet Will',text:" #|1|# is a document #|2|#"},
    // {title:'iCitizen',text:' #|2|# an individual of the Sweet Economy'},
    // {title:'Economy',text:' #|0|# or sweet economy'},
    // {title:'Sweet Will',text:" #|1|# is a document #|2|#"},
    // {title:'iCitizen',text:' #|2|# an individual of the Sweet Economy'},
    // {title:'Economy',text:' #|0|# or sweet economy'},
    // {title:'Sweet Will',text:" #|1|# is a document #|2|#"},
    // {title:'iCitizen',text:' #|2|# an individual of the Sweet Economy'},
    // {title:'Economy',text:' #|0|# or sweet economy'},
    // {title:'Sweet Will',text:" #|1|# is a document #|2|#"},
    // {title:'iCitizen',text:' #|2|# an individual of the Sweet Economy'},
    // {title:'Economy',text:' #|0|# or sweet economy'},
    // {title:'Sweet Will',text:" #|1|# is a document #|2|#"},
    // {title:'iCitizen',text:' #|2|# an individual of the Sweet Economy'},
    // {title:'Economy',text:' #|0|# or sweet economy'},
    // {title:'Sweet Will',text:" #|1|# is a document #|2|#"},
    // {title:'iCitizen',text:' #|2|# an individual of the Sweet Economy'},
    // {title:'Economy',text:' #|0|# or sweet economy'},
    // {title:'Sweet Will',text:" #|1|# is a document #|2|#"},
    // {title:'iCitizen',text:' #|2|# an individual of the Sweet Economy'},
    // {title:'Economy',text:' #|0|# or sweet economy'},
    // {title:'Sweet Will',text:" #|1|# is a document #|2|#"},
    // {title:'iCitizen',text:' #|2|# an individual of the Sweet Economy'},
    // {title:'Economy',text:' #|0|# or sweet economy'},
    // {title:'Sweet Will',text:" #|1|# is a document #|2|#"},
    // {title:'iCitizen',text:' #|2|# an individual of the Sweet Economy'},
    // {title:'Economy',text:' #|0|# or sweet economy'},
    // {title:'Sweet Will',text:" #|1|# is a document #|2|#"},
    // {title:'iCitizen',text:' #|2|# an individual of the Sweet Economy'},
    // {title:'Economy',text:' #|0|# or sweet economy'},
    // {title:'Sweet Will',text:" #|1|# is a document #|2|#"},
    // {title:'iCitizen',text:' #|2|# an individual of the Sweet Economy'},
    // {title:'Economy',text:' #|0|# or sweet economy'},
    // {title:'Sweet Will',text:" #|1|# is a document #|2|#"},
    // {title:'iCitizen',text:' #|2|# an individual of the Sweet Economy'},
    // {title:'Economy',text:' #|0|# or sweet economy'},
    // {title:'Sweet Will',text:" #|1|# is a document #|2|#"},
    // {title:'iCitizen',text:' #|2|# an individual of the Sweet Economy'},
    // {title:'Economy',text:' #|0|# or sweet economy'},
    // {title:'Economy',text:' #|0|# or sweet economy'},
    // {title:'Sweet Will',text:" #|1|# is a document #|2|#"},
    // {title:'iCitizen',text:' #|2|# an individual of the Sweet Economy'},
    // {title:'Economy',text:' #|0|# or sweet economy'},
];